try {
  cosnole.log('error')
} catch(e) {
  console.log(e)
}
